forecasting/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify, make_response, session
from flask_login import login_required, current_user
from .classes import UploadCSV, UploadValidationCSV, UploadRetrainingCSV
from werkzeug.utils import secure_filename
import os
from .secrets import BRANCH_DATA_FOLDER, PROFILE_PICTURES, LAST_FILE_UPLOADED, VALIDATION_DATA, RETRAINING_DATA, MERGED_DATA_FOLDER, MODELS
from datetime import datetime, date
from .models import User, UserSchema, Permissions, PermissionsSchema, Uploads, UploadsSchema, Forecast_data, ForecastDataSchema, Branches, BranchesSchema, Products, ProductsSchema, SettingsSchema, Settings, Validation_dataSchema, Validation_data, Retraining_dataSchema, Retraining_data, FinalData, ForecastingModelSchema, Forecasting_model
import json
from . import db, conn
from .retraining_process import *
from .functions import *
from sqlalchemy.exc import IntegrityError
from sqlalchemy.sql import func
from sqlalchemy import delete
from werkzeug.security import generate_password_hash
import csv
import pandas as pd
from sqlalchemy import create_engine, text # for truncating table
import shutil
from tensorflow.keras import models
import pickle

# Importing Image module from PIL package
from PIL import Image
import PIL

from flask_wtf import FlaskForm


views = Blueprint('views', __name__)

@views.route('/dashboard')
@login_required
def dashboard():
    session['current_menu'] = request.path
    return render_template("modules/dashboard.html", auth_user=current_user, permissions=permissions())

# @views.route('/forecasting')
# @login_required
# def forecasting():
#     session['current_menu'] = request.path # for active menu
#     return render_template("modules/forecasting/forecasting.html", auth_user=current_user,permissions=permissions())

#######################################################
#
# USERS MODULE ROUTE
#
#######################################################

@views.route('/users', methods=['GET', 'POST'], endpoint="users")
@login_required
def users():
    session['current_menu'] = request.path # for active menu
    if request.method == 'GET':
        search = request.args.getlist('search')
        search = (','.join(search))

        fstatus = request.args.getlist('status')
        fstatus = (','.join(fstatus))

        fposition = request.args.getlist('position')
        fposition = (','.join(fposition))

        # Set the pagination configuration
        page = request.args.get('page', 1, type=int)

        if search:
            users = db.session.query(User, Permissions).join(Permissions)\
                .filter((User.user_type != -1))\
                .filter((User.first_name.like('%' + search + '%'))      |
                        (User.middle_name.like('%' + search + '%'))     |
                        (User.last_name.like('%' + search + '%'))       |
                        (User.address.like('%' + search + '%'))         |
                        (User.contact_number.like('%' + search + '%'))  |
                        (User.company_name.like('%' + search + '%'))    |
                        (User.email.like('%' + search + '%')))\
                .paginate(page=page, per_page=10)
        elif fstatus:
            users = db.session.query(User, Permissions).join(Permissions)\
                .filter((User.user_type != -1))\
                .filter(User.is_active == (True if (fstatus == '1') else False))\
                .paginate(page=page, per_page=10)
        elif fposition:
            users = db.session.query(User, Permissions).join(Permissions)\
                .filter((User.user_type != -1))\
                .filter(User.user_type == fposition)\
                .paginate(page=page, per_page=10)
        else:
            users = db.session.query(User, Permissions).join(Permissions).filter((User.user_type != -1), (User.is_active != 0)).order_by(User.first_name.asc()).paginate(page=page, per_page=10)
        return render_template("modules/users/users.html",
                           auth_user=current_user,
                           users = users,
                           prev = '',
                           new_user = 'false',
                           update_user = 'false',
                           search = search,
                           fstatus = fstatus,
                           fposition = fposition,
                           permissions=permissions(),
                           current_model='',
                           forecast_models=[])

@views.route('/create-users', methods=['POST'])
@login_required
def create_users():
    session['current_menu'] = '/users'
    if request.method == 'POST':
        try:
            first_name = request.form['first_name']
            middle_name = request.form['middle_name']
            last_name = request.form['last_name']
            email = request.form['email']
            address = request.form['address']
            contact_number = request.form['contact_number']
            user_type = request.form['user_type']
            password = generate_password_hash(request.form['password'], method="sha256")

            new_user = User(first_name, middle_name, last_name, address, contact_number, 'WeTech', email, password, None, 'default.png' if user_type == 0 else 'personnel.png', user_type, 1)
            db.session.add(new_user)
            db.session.flush()
            user_id = new_user.id
            if request.form['user_type'] == '0':
                permission = Permissions(user_id, True, True, True, True, True, True, True, True, True, True)
                db.session.add(permission)
            elif request.form['user_type'] == '1':
                permission = Permissions(user_id, True, True, None, None, None, None, None, None, None, None)
                db.session.add(permission)

            db.session.commit()
            
            flash('New User Successfully Created!', category='success')
            return redirect(url_for('.users'))
        except IntegrityError:
            db.session.rollback()
            page = request.args.get('page', 1, type=int)
            flash('Email Already Taken', category='error')
            users = db.session.query(User, Permissions).join(Permissions).filter(User.user_type != -1).paginate(page=page, per_page=10)
            return render_template("modules/users/users.html", auth_user=current_user, users = users, prev = request.form.to_dict(), new_user = 'true', update_user = 'false', search = '', fstatus = '', fposition = '', permissions=permissions(), current_model='', forecast_models=[])

@views.route('/update-users', methods=['POST'])
@login_required
def update_users():
    session['current_menu'] = '/users'
    if request.method == 'POST':
        try:
            update_user = User.query.filter_by(id=request.form['user_id']).first()
            update_user.first_name = request.form['first_name']
            update_user.middle_name = request.form['middle_name']
            update_user.last_name = request.form['last_name']
            update_user.email = request.form['email']
            update_user.address = request.form['address']
            update_user.contact_number = request.form['contact_number']
            update_user.user_type = request.form['user_type']
            update_user.is_active = True if request.form['is_active'] == '1' else False

            if request.form['password'] != None:
                password = generate_password_hash(request.form['password'], method="sha256")
                update_user.password = password

            db.session.commit()
            
            flash('User Successfully Updated!', category='success')
            return redirect(url_for('.users'))
        except IntegrityError:
            db.session.rollback()
            page = request.args.get('page', 1, type=int)
            flash('Email Already Taken', category='error')
            users = db.session.query(User, Permissions).join(Permissions).filter(User.user_type != -1).paginate(page=page, per_page=10)
            return render_template("modules/users/users.html", auth_user=current_user, users = users, prev = request.form.to_dict(), new_user = 'false', update_user = 'true', search = '', fstatus = '', fposition = '', permissions=permissions(), current_model='', forecast_models=[])

@views.route('/delete-users', methods=['POST'])
@login_required
def delete_users():
    session['current_menu'] = '/users'
    delete_user = User.query.filter_by(id=request.form['user_id']).first()
    delete_permission = Permissions.query.filter_by(user_id=request.form['user_id']).first()
    db.session.delete(delete_permission)
    db.session.delete(delete_user)
    db.session.commit()
    
    flash('User Successfully Deleted!', category='success')
    return redirect(url_for('.users'))

@views.route('/permission-user', methods=['POST'])
@login_required
def user_permission():
    session['current_menu'] = '/users'
    permission = Permissions.query.filter_by(permission_id=request.form['permission_id']).first()
    permission.forecasting = True if request.form['forecasting'] == 'true' else False
    permission.user_c = True if request.form['user_c'] == 'true' else False
    permission.user_r = True if request.form['user_r'] == 'true' else False
    permission.user_u = True if request.form['user_u'] == 'true' else False
    permission.user_d = True if request.form['user_d'] == 'true' else False
    permission.user_p = True if request.form['user_p'] == 'true' else False
    permission.setting_c = True if request.form['setting_c'] == 'true' else False
    permission.setting_u = True if request.form['setting_u'] == 'true' else False
    permission.setting_d = True if request.form['setting_d'] == 'true' else False
    permission.uploading = True if request.form['uploading'] == 'true' else False
    db.session.commit()
    
    flash('Permissions Successfully Updated!', category='success')
    return redirect(url_for('.users'))

forecasting/templates/modules/users/delete_user.html
<div class="flex items-center justify-center bg-gray-700 bg-opacity-70 mx-auto overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 px-2 pt-2 h-screen" style="display: none" x-show="delete_user">
    <div class="flex flex-col relative w-full max-w-lg rounded-lg">
        <!-- MODAL -->
        <div class="relative w-full max-w-lg h-full md:h-auto bg-white rounded-lg">
            <!-- Modal content -->
            <div class="bg-white rounded-lg shadow dark:bg-gray-700 w-full">
                <div class="pt-3 pl-2 pb-3 bg-red-400 rounded-t-lg">
                    <h3 class="text-xl font-medium text-white dark:text-white">
                        Confirm Delete
                    </h3>
                </div>
                <button type="button" class="absolute top-3 right-2.5 text-red-200 bg-transparent hover:bg-red-200 hover:text-red-400 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" x-on:click="close_modal">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
            <!--<div class="m-2 p-2 mt-3 flex flex-col space-y-2">-->
            <div class="flex flex-col space-y-2">
                <div class="text-gray-900 flex flex-row items-center bg-gray-100">
                    <div class="m-3 mt-3 h-16 w-16 rounded-full border-2 border-gray-200 bg-red-200">
                        <img class="rounded-full" :src="avatar" />
                    </div>
                    <div class="flex flex-col border-r-2 border-gray-200 pr-10">
                        <span x-text="account_name" class="text-lg font-bold text-green-400"></span>
                        <span x-text="account_type" class="text-md text-gray-400"></span>
                    </div>
                    <div class="flex flex-col items-center pl-10">
                        <span class="text-lg font-bold text-gray-400">Account Status</span>
                        <span x-text="account_status" class="rounded-md text-white text-center px-3" :class="[account_status == 'Active' ? 'bg-green-400 w-20' : 'bg-red-400 w-20']"  ></span>
                    </div>
                </div>
                <div class="flex flex-col lg:flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0 mx-3">
                    <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="text" id="d_first_name" name="first_name" x-ref="d_first_name" placeholder="First Name" disabled hidden />
                    <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="text" id="d_middle_name" name="middle_name" x-ref="d_middle_name" value="" placeholder="Middle Name" disabled hidden />
                </div>
                <div class="flex flex-col lg:flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0 mx-3">
                    <div>
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="text" id="d_last_name" name="last_name" x-ref="d_last_name" value="" placeholder="Last Name" disabled hidden />
                    </div>
                </div>
                <div class="flex flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0 mx-3 justify-center">
                    <div class="py-7">
                        <h2 class="font-bold text-gray-400 text-center">
                            Are you sure you want to delete this account?
                        </h2>
                    </div>
                </div>
                <!--<div class="flex flex-col lg:flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0 mx-3">
                    <div class="w-full">
                        <label for="email" class="block text-sm font-medium text-gray-900 dark:text-gray-300">Address</label>
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="text" id="v_address" name="address" x-ref="v_address" value="" placeholder="Address" disabled />
                    </div>
                </div>
                <div class="flex flex-col lg:flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0 mx-3">
                    <div class="flex flex-col w-full">
                        <label for="email" class="block text-sm font-medium text-gray-900 dark:text-gray-300">Contact Number</label>
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="number" id="v_contact_number" name="contact_number" x-ref="v_contact_number" value="" placeholder="Contact Number" disabled />
                    </div>
                    <div class="flex flex-col w-full">
                        <label for="email" class="block text-sm font-medium text-gray-900 dark:text-gray-300">Email</label>
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="email" id="v_email" name="email" x-ref="v_email" value="" placeholder="Email" disabled />
                    </div>
                </div> -->
                <!--<div class="flex flex-col lg:flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0">
                    <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="password" id="v_password" name="password" x-ref="v_password" value="" placeholder="Password" disabled />
                    <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="password" id="v_confirm_password" name="confirm_password" x-ref="v_confirm_password" value="" placeholder="Confirm Password" disabled />
                </div>-->
                <form action="{{ url_for('views.delete_users') }}" method="POST" class="mx-auto">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <input id="d_user_id" name="user_id" x-ref="d_user_id" hidden>
                    <div class="mx-auto py-3">
                        <button type="submit" class="inline-flex items-center px-4 py-2 bg-red-400 border border-transparent rounded-lg font-semibold text-xs text-white uppercase tracking-widest hover:bg-red-400 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring ring-gray-300 disabled:opacity-25 transition ease-in-out duration-150" x-on:click="close_modal">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 -ml-1 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            Confirm
                        </button>
                        <button type="button" class="inline-flex items-center px-4 py-2 bg-gray-500 border border-transparent rounded-lg font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring ring-gray-300 disabled:opacity-25 transition ease-in-out duration-150" x-on:click="close_modal">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 -ml-1 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            Cancel
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

forecasting/templates/modules/users/new_user.html
<div class="flex items-center justify-center bg-gray-700 bg-opacity-70 mx-auto overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-screen px-2 pt-2" style="display: none" x-show="new_user">
    <div class="flex flex-col relative w-full max-w-lg rounded-lg">
        <!-- Flask Error Messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="flex flex-row relative w-full max-w-lg h-full md:h-auto bg-white rounded-md mb-3 px-2 py-2 bg-red-100" x-show="flask_error">
                            <svg xmlns="http://www.w3.org/2000/svg" class="text-red-400 h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            <span class="text-red-400">{{ message }}!</span>
                            <button type="button" class="top-3 right-2.5 text-gray-400 bg-transparent hover:bg-red-200 hover:text-red-400 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" x-on:click="flask_error = false">
                                <svg aria-hidden="true" class="w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                                <span class="sr-only">Close modal</span>
                            </button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
        <!-- Alpine Error Messages -->
        <div class="flex flex-row relative w-full max-w-lg h-full md:h-auto bg-white rounded-md mb-3 px-2 py-2 bg-red-100" style="display: none" x-show="user_error">
            <svg xmlns="http://www.w3.org/2000/svg" class="text-red-400 h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span class="text-red-400" x-text="user_error_message"></span>
            <button type="button" class="top-3 right-2.5 text-gray-400 bg-transparent hover:bg-red-200 hover:text-red-400 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" x-on:click="user_error = false">
                <svg aria-hidden="true" class="w-3 h-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                <span class="sr-only">Close modal</span>
            </button>
        </div>

        <!-- MODAL -->
        <div class="relative w-full max-w-lg h-full md:h-auto bg-white rounded-lg">
            <!-- Modal content -->
            <div class="bg-white rounded-lg shadow dark:bg-gray-700 w-full">
                <div class="pt-3 pl-2 pb-3 bg-green-400 rounded-t-lg">
                    <h3 class="text-xl font-medium text-white dark:text-white">
                        Create New User
                    </h3>
                </div>
                {% if new_user == 'true'  %}
                    <a href="{{ url_for('views.users') }}" class="absolute top-3 right-2.5 text-green-200 bg-transparent hover:bg-green-200 hover:text-green-400 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white">
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        <span class="sr-only">Close modal</span>
                    </a>
                {% else %}
                    <button type="button" class="absolute top-3 right-2.5 text-green-200 bg-transparent hover:bg-green-200 hover:text-green-400 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" x-on:click="new_user = false">
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                        <span class="sr-only">Close modal</span>
                    </button>
                {% endif %}
            </div>
            <form action="{{ url_for('views.create_users') }}" method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <div class="m-2 p-2 mt-3 flex flex-col space-y-2">
                    <div class="flex flex-col lg:flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0">
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="text" id="first_name" name="first_name" value="{{ prev.first_name if prev }}" placeholder="First Name" autocomplete="off" required />
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="text" id="middle_name" name="middle_name" value="{{ prev.middle_name if prev }}" placeholder="Middle Name" autocomplete="off" />
                    </div>
                    <div class="flex flex-col lg:flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0">
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="text" id="last_name" name="last_name" value="{{ prev.last_name if prev }}" placeholder="Last Name" autocomplete="off" required />
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="email" id="email" name="email" value="{{ prev.email if prev }}" placeholder="Email" autocomplete="off" required />
                    </div>
                    <div class="flex flex-col lg:flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0">
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="text" id="address" name="address" value="{{ prev.address if prev }}" placeholder="Address" autocomplete="off" required />
                    </div>
                    <div class="flex flex-col lg:flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0">
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="number" id="contact_number" name="contact_number" value="{{ prev.contact_number if prev }}" placeholder="Contact Number" autocomplete="off" required />
                        <select class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="text" id="user_type" name="user_type">
                            {% if prev %}
                                <option value="{{ prev.user_type }}" selected hidden>{{ 'Admin' if prev.user_type == '0' else 'Personnel' }}</option>
                            {% else %}
                                <option value="" selected hidden>-- Select User Type --</option>
                            {% endif %}
                            <option value="0">Admin</option>
                            <option value="1">Personnel</option>
                        </select>
                    </div>
                    <div class="flex flex-col lg:flex-row space-x-0 lg:space-x-2 space-y-2 lg:space-y-0">
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="password" id="password" name="password" x-ref="n_password" value="" placeholder="Password" autocomplete="off" required />
                        <input class="w-full text-sm rounded-lg shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" type="password" id="confirm_password" name="confirm_password" x-ref="n_confirm_password" value="" placeholder="Confirm Password" autocomplete="off" required />
                    </div>
                    <div>
                        <button x-ref="save" x-on:click="submit_new_user" type="button" class="inline-flex items-center px-4 py-2 bg-green-500 border border-transparent rounded-lg font-semibold text-xs text-white uppercase tracking-widest hover:bg-green-400 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring ring-gray-300 disabled:opacity-25 transition ease-in-out duration-150">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 -ml-1 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            Save
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>